version: '3.8'

services:
  nginx1:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html1:/usr/share/nginx/html
    restart: always

  nginx2:
    image: nginx:alpine
    ports:
      - "90:80"
    depends_on:
      - nginx1
    restart: always
